### ISSUE TITLE
Resuming this Project

### ISSUE THREAD

**Issue by mbouli** [RileyDatLord/ghdo#13]
I think that me and Riley should start working on this project again. It was very fun in the beginning to work on this. So hopefully we can work on this soon

**Comment by ReportCardsMC** [comment]
I would love to also, currently cannot but should be able to within a week or 2, because by then I am getting a new computer

**Comment by ReportCardsMC** [comment]
To resume this project, I would need more funding for a domain renewal soon, also when/if I am able to I plan on redoing every thing about ghdo, the website, backend, etc.

**Comment by ReportCardsMC** [comment]
Domains don’t cost too much just a couple bucks

**Comment by mbouli** [comment]
@RileyDatLord True that. Hopefully we can rework this. Because I have learned much from when we began this website and I would love to redo this and maybe make the domain automatic when we accept pull request and then it adds to the domain. This may be possible because JS.ORG most likely does it and I have seen a few cloudflare apis. If not its fine doing it manually.
