### ISSUE TITLE
Needing a new logo

### ISSUE THREAD

**Issue by ReportCardsMC** [RileyDatLord/ghdo#3]
We need a cool logo made for us, as we have none right now, if you would like to make one for free you can, once finished please send the finished product to Riley#9999 on Discord 👍

**Comment by ggcarlosr** [comment]
Hello, I am available to help create a logo that identifies them. what would the requirements be and what does the project deal with?

**Comment by ReportCardsMC** [comment]
The idea of the logo we need is something along of the lines of websites, and must have the text "GD" in the middle we don't matter what style it is, just do what you find best.

**Comment by ggcarlosr** [comment]
Hey man, the application for your repo logo is no longer open.

**Comment by mbouli** [comment]
We have recieved a new logo ;D.
